blank_issues_enabled: false
contact_links:
  - name: ğŸ“˜ Documentation
    url: https://www.defined.net/nebula/
    about: Review documentation.

  - name: ğŸ’ Support
    url: https://join.slack.com/t/nebulaoss/shared_invite/enQtOTA5MDI4NDg3MTg4LTkwY2EwNTI4NzQyMzc0M2ZlODBjNWI3NTY1MzhiOThiMmZlZjVkMTI0NGY4YTMyNjUwMWEyNzNkZTJmYzQxOGU
    about: 'This issue tracker is not for support questions. Join us on Slack for assistance!'
